language: python
python:
  - "3.6"
env:
  - SETTINGS_DIR="easy_internship_api/easy_internship_api"
before_install:
  - cp $SETTINGS_DIR/config.template.py $SETTINGS_DIR/config.py
install:
  - pip install -r requirements.txt
script:
  - python easy_internship_api/manage.py test easy_internship_api