# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-16 18:58
from __future__ import unicode_literals

import centers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(centers.models.SubmissionRestriction, models.Model),
        ),
        migrations.CreateModel(
            name='PositionLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TimeRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(centers.models.SubmissionRestriction, models.Model),
        ),
    ]
