# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-16 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traineecategory',
            old_name='profile_format_id',
            new_name='profile_schema_id',
        ),
    ]
