# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingperiod',
            name='duration_units',
            field=models.CharField(choices=[('months', 'months'), ('years', 'years')], default='years', max_length=6),
        ),
        migrations.AlterField(
            model_name='trainingperiod',
            name='duration_value',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
